name: learn-github-actions
on:
  push:
    branches:
      - develop

jobs:
  validate-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2
          php-version: '8'

      - name: Validate composerssdf
        run: composer validate --strict

      - name: Run composer install
        run: composer install

      - name: Run unit tests
        run: ./vendor/bin/phpunit -c phpunit.xml

      - name: Run php lint on production files
        run: php -l src -q

      - name: Run php lint on test files
        run: php -l tests -q